### ISSUE TITLE
App crash when open release in notifications menu

### ISSUE THREAD

**Issue by Douile** [ThirtyDegreesRay/OpenHub#135]
When a release is pressed in the notifications menu the app crashes.

(dark mode) v2.8.0

**Comment by Kelvino9** [comment]
I got the same issue in v3.0.0

**Comment by pzhlkj6612** [comment]
OpenHub v3.0.0
Android 6.0.1

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.thirtydegreesray.openhub.mvp.model.NotificationSubject$Type.ordinal()' on a null object reference
	at com.thirtydegreesray.openhub.ui.fragment.q.onItemClick(Unknown Source)
	at com.thirtydegreesray.openhub.ui.adapter.base.a.onItemClick(Unknown Source)
	at com.thirtydegreesray.openhub.ui.adapter.base.b.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5215)
	at android.view.View$PerformClick.run(View.java:21196)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```
